// Offline support.
//
// The whole point of a pocket guide is being abroad without data, so the app has
// to work with the network off -- including export, which is why every renderer is
// client-side. The shell is precached on install; a language's corpus and fonts
// are two megabytes or so per script, far too much to cache speculatively, so they
// are fetched on request from the gallery's "save for offline".
//
// Scoped to /pocket-language-guide/, so nothing else on the site is affected.

// The precache list and VERSION are generated by scripts/build_shell.mjs from what
// is actually on disk (`npm run shell`). It used to be a hand-written array here,
// and it drifted: seven modules were missing, so the studio would have failed with
// the network off. VERSION is a content hash of those files, so a deploy re-primes
// the cache without anyone remembering to bump anything.
const VERSION = 'plg-8f0624031644';
const SHELL_CACHE = `${VERSION}-shell`;
const PACK_CACHE = `${VERSION}-packs`;
const SHELL_MANIFEST = 'data/shell.json';

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    const response = await fetch(SHELL_MANIFEST, { cache: 'reload' });
    const files = ['./', SHELL_MANIFEST, ...(await response.json()).files];
    // addAll fails the whole install if any single request fails, which would
    // leave no service worker at all; cache what we can and report the rest.
    const results = await Promise.allSettled(files.map((url) => cache.add(url)));
    const failed = files.filter((_, i) => results[i].status === 'rejected');
    if (failed.length) console.warn('[plg] shell files not cached:', failed);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (!key.startsWith(VERSION)) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  // Stale-while-revalidate: instant offline, and a background refresh means a
  // deploy is picked up on the next visit without a hard reload.
  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    const fresh = fetch(request).then(async (response) => {
      if (response.ok) {
        const cache = await caches.open(url.pathname.includes('/data/') || url.pathname.includes('/packs/')
          ? PACK_CACHE : SHELL_CACHE);
        cache.put(request, response.clone());
      }
      return response;
    }).catch(() => null);

    if (cached) return cached;
    const response = await fresh;
    if (response) return response;
    return new Response('Offline and this file was never cached.', {
      status: 504, headers: { 'content-type': 'text/plain' },
    });
  })());
});

// The gallery asks for a language's data and fonts explicitly, so a reader
// chooses what to carry rather than downloading every script.
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || data.type !== 'cache-urls') return;
  event.waitUntil((async () => {
    const cache = await caches.open(PACK_CACHE);
    const results = await Promise.allSettled(data.urls.map((/** @type {string} */ u) => cache.add(u)));
    const failed = data.urls.filter((/** @type {string} */ _, /** @type {number} */ i) => results[i].status === 'rejected');
    event.source?.postMessage({
      type: 'cache-urls-done', ok: failed.length === 0, failed, total: data.urls.length,
    });
  })());
});
