// Offline support.
//
// The whole point of a pocket guide is being abroad without data, so the app has
// to work with the network off -- including export, which is why every renderer is
// client-side. The shell is precached on install; a language's corpus and fonts
// are two megabytes or so per script, far too much to cache speculatively, so they
// are fetched on request from the gallery's "save for offline".
//
// Scoped to /pocket-language-guide/, so nothing else on the site is affected.

// The precache list and VERSION are generated by scripts/build_shell.mjs from what
// is actually on disk (`npm run shell`). It used to be a hand-written array here,
// and it drifted: seven modules were missing, so the studio would have failed with
// the network off. VERSION is a content hash of those files, so a deploy re-primes
// the cache without anyone remembering to bump anything.
const VERSION = 'plg-1aa3f1239802';
const SHELL_CACHE = `${VERSION}-shell`;
/**
 * **Not version-scoped, deliberately.** The shell has to be replaced wholesale on a
 * deploy or a reader gets last week's modules against this week's data. A saved
 * language pack is the opposite: it is the corpus rows and the subset fonts for one
 * pair, it is megabytes, and someone pressed a button to get it -- usually before
 * going somewhere without a network, which is the whole reason the button exists.
 * Scoping this to `VERSION` meant a one-character CSS change silently discarded
 * every pack every reader had saved, because `VERSION` is a content hash of the
 * *shell*.
 *
 * The trade is that a pack can outlive a change to the data it holds. That is
 * survivable in a way the reverse is not: `data/coverage.json` and the registry are
 * in the shell, so a language whose rows changed shape still loads, and a reader who
 * wants the new rows can press the button again.
 */
const PACK_CACHE = 'plg-packs';
/** The prefix every cache of ours carries, which is what tells them apart from every
 * other app's on this origin. `VERSION` already begins with it. */
const OURS = 'plg-';
const SHELL_MANIFEST = 'data/shell.json';

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(SHELL_CACHE);
    const response = await fetch(SHELL_MANIFEST, { cache: 'reload' });
    const files = ['./', SHELL_MANIFEST, ...(await response.json()).files];
    // **A partial shell must not become the active one.** This used to cache what it
    // could and warn about the rest, on the reasoning that failing the install
    // "would leave no service worker at all". That reasoning is backwards: a
    // rejected install does not activate, so the *previous* worker keeps serving
    // from its own complete cache. Half-installing and then activating is what
    // leaves nothing -- `activate` deletes the old shell, so one failed download
    // during a deploy replaced a working offline copy with a broken one, which is
    // the exact case this app exists for.
    //
    // So the install fails loudly and the reader keeps what they had. The names are
    // still reported, because "the deploy is incomplete" is worth seeing in a console.
    const results = await Promise.allSettled(files.map((url) => cache.add(url)));
    const failed = files.filter((_, i) => results[i].status === 'rejected');
    if (failed.length) {
      console.warn('[plg] shell incomplete, keeping the previous version:', failed);
      // Drop the half-built cache so a later attempt starts clean rather than
      // inheriting whichever files happened to arrive this time.
      await caches.delete(SHELL_CACHE);
      throw new Error(`shell incomplete: ${failed.length} of ${files.length} files`);
    }
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      // **Only this app's own caches.** Cache Storage is scoped to the *origin*, not
      // to a service worker's scope, and vetr.dev serves several apps from the same
      // one -- so deleting everything that is not one of our two names was deleting
      // caches belonging to whatever else happens to be there. Nothing else on the
      // origin uses Cache Storage today, which is the only reason this never showed;
      // the next app to add a service worker would have lost its cache silently.
      //
      // Ours are the ones carrying our prefix, and the two current names are kept.
      if (!key.startsWith(OURS)) continue;
      if (key !== SHELL_CACHE && key !== PACK_CACHE) await caches.delete(key);
    }

    // **Nothing the shell owns may also sit in the pack cache.** The fetch handler
    // below used to revalidate every `/data/` path into `PACK_CACHE`, and that is
    // 221 of the 278 shell files -- the whole registry, all 66 respell tables, all
    // 48 interface catalogues, the theme. `caches.match` searches caches in
    // creation order, and the pack cache outlives a deploy by design, so that copy
    // shadowed the version-scoped one and a deploy did *not* replace it. It is the
    // exact failure the comment on `PACK_CACHE` says is not survivable: last
    // week's modules against this week's data, or worse, this week's
    // `languages.csv` against last week's `scripts.csv` -- which names a script
    // row that does not exist yet and took the studio down with `Cannot read
    // properties of undefined (reading 'font_stack')`.
    //
    // Stopping it at the source is not enough, because every existing reader is
    // already carrying the duplicates. They are dropped here. Nothing a reader
    // saved is lost: `data/concepts/` and `data/lang/` are not in the shell
    // manifest, so a saved pack's rows and its subset fonts are not touched, and
    // the two font files that *are* in the shell keep their shell copy.
    const shell = await caches.open(SHELL_CACHE);
    const pack = await caches.open(PACK_CACHE);
    for (const request of await pack.keys()) {
      if (await shell.match(request, { ignoreSearch: true })) await pack.delete(request);
    }

    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== location.origin) return;

  // Stale-while-revalidate: instant offline, and a background refresh means a
  // deploy is picked up on the next visit without a hard reload.
  event.respondWith((async () => {
    const cached = await caches.match(request, { ignoreSearch: true });
    const fresh = fetch(request).then(async (response) => {
      if (response.ok) {
        // Refresh the file in whichever cache already owns it. A shell file stays
        // in the version-scoped shell, so a deploy really does replace it; a
        // language's rows, its subset fonts and the gallery's thumbnails stay in
        // the pack cache, which outlives a deploy on purpose.
        //
        // Asking the shell rather than testing the path is what makes this right.
        // `data/registry/scripts.csv` is a shell file and `data/lang/km/core.csv`
        // is not, and no prefix tells them apart -- which is why the `/data/` test
        // this replaces sent two thirds of the shell to the wrong cache.
        const shell = await caches.open(SHELL_CACHE);
        const owner = (await shell.match(request, { ignoreSearch: true }))
          ? shell
          : await caches.open(PACK_CACHE);
        owner.put(request, response.clone());
      }
      return response;
    }).catch(() => null);

    if (cached) return cached;
    const response = await fresh;
    if (response) return response;
    return new Response('Offline and this file was never cached.', {
      status: 504, headers: { 'content-type': 'text/plain' },
    });
  })());
});

// The gallery asks for a language's data and fonts explicitly, so a reader
// chooses what to carry rather than downloading every script.
self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || data.type !== 'cache-urls') return;
  event.waitUntil((async () => {
    const cache = await caches.open(PACK_CACHE);
    const shell = await caches.open(SHELL_CACHE);
    // **Skip what the shell already has.** A pair needs its reader's respelling
    // overrides and the Latin face, and both of those are shell files -- already
    // precached, already offline, and nothing here can make them more so. Copying
    // them puts the same file in both caches, which is the shadowing `activate`
    // exists to remove: the pack cache is not version-scoped and answers first, so
    // the copy would outlive the deploy meant to replace it.
    //
    // They still count toward `total`, because the reader asked for a pair and got
    // one; what is reported is whether the pair is saved, not how many requests it
    // took.
    /** @type {string[]} */ const wanted = [];
    for (const url of data.urls) {
      if (!(await shell.match(url, { ignoreSearch: true }))) wanted.push(url);
    }
    const results = await Promise.allSettled(wanted.map((u) => cache.add(u)));
    const failed = wanted.filter((/** @type {string} */ _, /** @type {number} */ i) => results[i].status === 'rejected');
    event.source?.postMessage({
      type: 'cache-urls-done', ok: failed.length === 0, failed, total: data.urls.length,
    });
  })());
});
