export function createInitialState() {
  return {
    currentColors: [],
    newColors: [],
    rawCurrentColors: [],
    rawNewColors: [],
    rawBestColors: [],
    optimizedColorRoles: [],
    rawSpace: null,
    newRawSpace: null,
    running: false,
    bestScores: [],
    copyTimeout: null,
    lastRuns: 0,
    bounds: null,
    mutedInput: false,
    nmTrails: [],
    bestColors: [],
    runResults: [],
    runRanking: [],
    selectedResultIdx: null,
    customConstraints: null,
    customConstraintSelection: null,
    sliderConstraintBounds: null,
    preserveSliderConstraintBoundsOnce: false,
    imageInput: null,
    suppressConstraintTopologyHistory: false,
    perInputConstraints: {
      enabled: false,
      autoEnabledForTweaks: false,
      sync: { h: false, sc: false, l: false },
      widths: { h: [], sc: [], l: [] },
      modes: [],
    },
    tweakInputIndices: [],
    hoveredTweakInputIndex: null,
  };
}
