// Generate the service worker's precache list.
//
//   npm run shell
//
// This was a hand-written array in sw.js, and it drifted the moment a module was
// added: seven shipped files were missing, so the studio would have failed with the
// network off -- the one situation the app exists for. The list is now derived from
// what is actually on disk, and its version is a hash of those files' contents, so
// the worker re-primes when any of them changes.
//
// Language data and packs are deliberately excluded: they are megabytes per
// language and are cached on request by the gallery's "Save offline".
//
// `--check` verifies the committed files are current instead of rewriting them, so
// `npm run check` catches a module that was added without regenerating.
import { readFile, writeFile, readdir, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const CHECK = process.argv.includes('--check');
const INDEX_PATH = 'data/respell/overrides/index.json';
const RULES_INDEX_PATH = 'data/respell/rules/index.json';

/** Directories whose contents belong in the shell, searched recursively. */
const CODE_DIRS = ['core', 'render', 'ui'];

/** Individual files the app cannot start without. */
const ENTRY_FILES = [
  'index.html', 'sheet.html', 'customize.html', 'style.css',
  'favicon.svg', 'manifest.webmanifest',
  'vendor/fontkit.esm.js', 'vendor/pdf-lib.esm.js',
  'data/presets.json', 'data/icons.json', 'data/coverage.json',
  'data/fonts/manifest.json',
  'packs/index.json',
  'data/respell/overrides/index.json',
];

/** Everything in these directories, non-recursively. */
// data/i18n is in here because the interface has to keep working offline in the
// reader's own language, not fall back to English the moment the network goes.
const DATA_DIRS = ['data/registry', 'data/registry/section-titles',
  'data/registry/emergency-labels', 'data/themes', 'data/respell/overrides',
  'data/respell/rules', 'data/i18n'];

/** @param {string} dir @returns {Promise<string[]>} */
async function walk(dir) {
  /** @type {string[]} */ const out = [];
  for (const entry of await readdir(join(ROOT, dir), { withFileTypes: true })) {
    const rel = `${dir}/${entry.name}`;
    if (entry.isDirectory()) out.push(...await walk(rel));
    else if (entry.name.endsWith('.js')) out.push(rel);
  }
  return out;
}

// A Set because the generated respell index is named explicitly (it may not exist
// yet on a fresh checkout) and is also found by the data-directory scan once it
// does; without dedup the first run and every run after it disagreed.
const files = [...new Set([
  ...ENTRY_FILES,
  ...(await Promise.all(CODE_DIRS.map(walk))).flat(),
  ...(await Promise.all(DATA_DIRS.map(async (dir) => (await readdir(join(ROOT, dir)))
    .filter((f) => f.endsWith('.csv') || f.endsWith('.json'))
    .map((f) => `${dir}/${f}`)))).flat(),
])].sort();

// Which curated respelling files exist. Without this the app guessed, and asking
// for `zh-Hans__ja__ja-US.csv` -- a pair nobody has hand-curated -- 404ed on the
// happy path and left "Save offline" stuck on "Partly saved".
const overrides = files
  .filter((f) => f.startsWith('data/respell/overrides/') && f.endsWith('.csv'))
  .map((f) => f.slice('data/respell/overrides/'.length, -'.csv'.length));
const overrideIndex = `${JSON.stringify(overrides, null, 2)}\n`;

// And which reading languages have a respelling rule table. Most do not yet, and a
// pair whose reader has none simply gets no generated respelling -- so this list is
// what stops the app asking for sixteen files that were never written.
const ruleTables = files
  .filter((f) => f.startsWith('data/respell/rules/') && f.endsWith('.json')
    && !f.endsWith('/index.json'))
  .map((f) => f.slice('data/respell/rules/'.length, -'.json'.length));
const rulesIndex = `${JSON.stringify(ruleTables, null, 2)}\n`;

// This script's own output, so write it before checking that the list is real.
if (!CHECK) {
  await writeFile(join(ROOT, INDEX_PATH), overrideIndex);
  await writeFile(join(ROOT, RULES_INDEX_PATH), rulesIndex);
}

// Fail loudly rather than shipping a worker that precaches a 404.
const missing = [];
for (const file of files) {
  try {
    await stat(join(ROOT, file));
  } catch {
    missing.push(file);
  }
}
if (missing.length) {
  throw new Error(`shell list names files that do not exist: ${missing.join(', ')}`);
}

const hash = createHash('sha256');
for (const file of files) {
  hash.update(file);
  hash.update(await readFile(join(ROOT, file)));
}
const version = hash.digest('hex').slice(0, 12);

const manifest = `${JSON.stringify({
  note: 'Generated by scripts/build_shell.mjs. Do not edit.',
  version,
  files,
}, null, 2)}\n`;

// The browser only re-runs install when sw.js itself changes, so the version has
// to live in the worker too.
const swPath = join(ROOT, 'sw.js');
const sw = await readFile(swPath, 'utf8');
const nextSw = sw.replace(/^const VERSION = '[^']*';$/m, `const VERSION = 'plg-${version}';`);
if (nextSw === sw && !sw.includes(`plg-${version}`)) {
  throw new Error('could not find the VERSION line in sw.js');
}

if (CHECK) {
  const onDisk = await readFile(join(ROOT, 'data/shell.json'), 'utf8').catch(() => '');
  const indexOnDisk = await readFile(join(ROOT, INDEX_PATH), 'utf8').catch(() => '');
  const rulesOnDisk = await readFile(join(ROOT, RULES_INDEX_PATH), 'utf8').catch(() => '');
  if (onDisk !== manifest || nextSw !== sw || indexOnDisk !== overrideIndex
    || rulesOnDisk !== rulesIndex) {
    throw new Error('data/shell.json is stale -- run `npm run shell` and commit the result');
  }
  console.log(`shell manifest current  ${files.length} files, version plg-${version}`);
} else {
  await writeFile(join(ROOT, 'data/shell.json'), manifest);
  await writeFile(swPath, nextSw);
  console.log(`data/shell.json  ${files.length} files, version plg-${version}`);
}
