// The logo as path data, for the cards.
//
// `data/brand/mark.svg` is the one drawing of the mark: flat absolute paths, with no
// transform, clip or group, because neither card renderer applies a transform to a
// path. This writes it out as the path data the PDF and SVG renderers draw a
// `PathMark` from, scaled to a box one point tall, from which `logoMarks` in
// core/solve/index.js scales it to the band's type size.
//
//   node scripts/build_logo.mjs        writes core/logo-shapes.js

import { readFileSync, writeFileSync } from 'node:fs';

const svg = readFileSync(new URL('../data/brand/mark.svg', import.meta.url), 'utf8');
const view = /viewBox="([\d.-]+) ([\d.-]+) ([\d.-]+) ([\d.-]+)"/.exec(svg);
if (!view) throw new Error('data/brand/mark.svg has no viewBox');
const [vx, vy, vw, vh] = view.slice(1).map(Number);
/** @param {number} n */
const fmt = (n) => Number(n.toFixed(4)).toString();

// Absolute M/L/C/Z only, so every number is an x or a y in turn.
const shapes = [...svg.matchAll(/<path fill="(#[0-9a-f]{6})" d="([^"]+)"\/>/g)].map(([, fill, d]) => {
  if (/[^MLCZ\d\s.e-]/.test(d)) throw new Error(`mark.svg: a path is not absolute M/L/C/Z: ${d.slice(0, 40)}`);
  let k = 0;
  const unit = d.replace(/-?[\d.]+(?:e-?\d+)?/g, (n) => fmt((Number(n) - (k++ % 2 ? vy : vx)) / vh));
  return { d: unit, fill };
});
if (!shapes.length) throw new Error('data/brand/mark.svg has no paths');

const out = `// Generated by scripts/build_logo.mjs from data/brand/mark.svg -- do not edit.
//
// The mark as flat path data in a box one point tall and \`LOGO_ASPECT\` wide, in
// paint order. Coordinates alternate x, y throughout, which is what lets
// \`logoMarks\` scale and place it with one pass over the numbers.

export const LOGO_ASPECT = ${fmt(vw / vh)};

/** @type {{d:string, fill:string, stroke?:string, strokeWidth?:number}[]} */
export const LOGO_SHAPES = ${JSON.stringify(shapes, null, 2)};
`;
writeFileSync(new URL('../core/logo-shapes.js', import.meta.url), out);
console.log(`core/logo-shapes.js: ${shapes.length} shapes, aspect ${fmt(vw / vh)}`);
