// Extract just the Lucide icons the section registry uses into data/icons.json.
//
//   npm run icons
//
// Lucide is ISC-licensed monoline SVG: geometry, not a webfont, so the same data
// draws in the DOM preview, in exported SVG, and as vector paths in the PDF. Only
// the icons the registry actually references are committed.
//
// Every shape is normalised to a path `d` string here rather than in the
// renderers, so all three consume one uniform form and none of them needs to know
// what a <circle> is.
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { parseTable } from '../core/csv.js';

const SRC = 'node_modules/lucide-static/icons';

/** @param {string} tag @param {Record<string,string>} a */
function toPath(tag, a) {
  const n = (/** @type {string} */ k, /** @type {number} */ d = 0) => (a[k] === undefined ? d : Number(a[k]));
  switch (tag) {
    case 'path':
      return a.d;
    case 'line':
      return `M${n('x1')} ${n('y1')}L${n('x2')} ${n('y2')}`;
    case 'polyline':
    case 'polygon': {
      const pts = a.points.trim().split(/[\s,]+/).map(Number);
      let d = `M${pts[0]} ${pts[1]}`;
      for (let i = 2; i < pts.length; i += 2) d += `L${pts[i]} ${pts[i + 1]}`;
      return tag === 'polygon' ? `${d}Z` : d;
    }
    case 'circle':
    case 'ellipse': {
      const [cx, cy] = [n('cx'), n('cy')];
      const rx = tag === 'circle' ? n('r') : n('rx');
      const ry = tag === 'circle' ? n('r') : n('ry');
      return `M${cx - rx} ${cy}a${rx} ${ry} 0 1 0 ${rx * 2} 0a${rx} ${ry} 0 1 0 ${-rx * 2} 0Z`;
    }
    case 'rect': {
      const [x, y, w, h] = [n('x'), n('y'), n('width'), n('height')];
      const r = Math.min(n('rx', n('ry')), w / 2, h / 2);
      if (!r) return `M${x} ${y}h${w}v${h}h${-w}Z`;
      return `M${x + r} ${y}h${w - 2 * r}a${r} ${r} 0 0 1 ${r} ${r}`
        + `v${h - 2 * r}a${r} ${r} 0 0 1 ${-r} ${r}`
        + `h${-(w - 2 * r)}a${r} ${r} 0 0 1 ${-r} ${-r}`
        + `v${-(h - 2 * r)}a${r} ${r} 0 0 1 ${r} ${-r}Z`;
    }
    default:
      throw new Error(`unhandled SVG element <${tag}> in a Lucide icon`);
  }
}

const rows = parseTable(await readFile('data/registry/sections.csv', 'utf8'), 'sections.csv');
const wanted = [...new Set(rows.map((r) => r.icon).filter(Boolean))].sort();

const available = new Set(await readdir(SRC));
const missing = wanted.filter((name) => !available.has(`${name}.svg`));
if (missing.length) throw new Error(`no such Lucide icon: ${missing.join(', ')}`);

/** @type {Record<string,string[]>} */ const paths = {};
for (const name of wanted) {
  const svg = await readFile(`${SRC}/${name}.svg`, 'utf8');
  const body = svg.replace(/^[\s\S]*?<svg[^>]*>/, '').replace(/<\/svg>[\s\S]*$/, '');
  /** @type {string[]} */ const out = [];
  for (const el of body.matchAll(/<(\w+)([^>]*?)\/?>/g)) {
    /** @type {Record<string,string>} */ const attrs = {};
    for (const at of el[2].matchAll(/([\w-]+)="([^"]*)"/g)) attrs[at[1]] = at[2];
    out.push(toPath(el[1], attrs));
  }
  if (!out.length) throw new Error(`icon ${name} produced no geometry`);
  paths[name] = out;
}

const icons = {
  note: 'Generated by scripts/extract_icons.mjs. Do not edit.',
  license: 'ISC (Lucide)',
  viewBox: 24,
  strokeWidth: 2,
  linecap: 'round',
  linejoin: 'round',
  paths,
};
await writeFile('data/icons.json', `${JSON.stringify(icons, null, 2)}\n`);
console.log(`data/icons.json  ${wanted.length} icons, ${Object.values(paths).flat().length} paths`);
