#!/usr/bin/env python3
"""Fold verified emergency numbers into the region registry.

    python3 scripts/merge_regions.py tmp/regions/*.json

`data/registry/regions.csv` prints a region's numbers only at `confidence >= 2`, so
raising a row is a claim that an authoritative source confirms it. This script keeps
that honest: it refuses to write a `2` without both a `source` and a `verified_at`,
which is the same rule `scripts/validate_data.py` enforces on the way out.

The URL and the note each verifier recorded do not go in the CSV -- the cell has to
fit one line of a pocket card -- so they are written to
`data/registry/regions-sources.md` alongside, which is where a later reviewer looks
to re-check a number rather than researching it again from scratch.
"""
import argparse
import csv
import datetime
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / "data"
CSV_PATH = DATA / "registry/regions.csv"
NOTES_PATH = DATA / "registry/regions-sources.md"


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("proposals", nargs="+")
    args = ap.parse_args(argv[1:])

    with CSV_PATH.open(encoding="utf-8-sig", newline="") as fh:
        reader = csv.DictReader(fh)
        header = list(reader.fieldnames or [])
        rows = {r["iso3166"]: r for r in reader}

    today = datetime.date.today().isoformat()
    verified = []
    errors = []
    changed = 0

    for path in args.proposals:
        doc = json.loads(Path(path).read_text(encoding="utf-8"))
        group = Path(path).stem
        for entry in doc.get("regions", []):
            code = entry["iso3166"]
            row = rows.get(code)
            if row is None:
                errors.append(f"{group}: {code} is not in regions.csv")
                continue
            confidence = int(entry.get("confidence", 1))
            source = (entry.get("source") or "").strip()
            if confidence >= 2 and not source:
                errors.append(f"{group}: {code} claims confidence {confidence} with no source")
                continue

            before = (row["emergency_numbers"], row["currency"], row["confidence"])
            row["emergency_numbers"] = entry.get("emergency_numbers", row["emergency_numbers"])
            row["currency"] = entry.get("currency", row["currency"])
            row["confidence"] = str(confidence)
            row["source"] = source or row["source"]
            # Only a verified row gets dated. An unverified one keeps an empty date,
            # which is what tells the next reviewer it still needs looking at.
            row["verified_at"] = today if confidence >= 2 else ""
            if (row["emergency_numbers"], row["currency"], row["confidence"]) != before:
                changed += 1
            verified.append({
                "code": code, "name": row["name_en"], "group": group,
                "numbers": row["emergency_numbers"], "currency": row["currency"],
                "confidence": confidence, "source": source,
                "url": entry.get("url", ""), "note": entry.get("note", ""),
            })

    if errors:
        for e in errors:
            print(f"error  {e}", file=sys.stderr)
        return 1

    with CSV_PATH.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=header, lineterminator="\r\n")
        w.writeheader()
        w.writerows(rows.values())

    lines = [
        "# Where each region's emergency numbers came from",
        "",
        "Generated by `scripts/merge_regions.py`. The CSV cell has to fit one line of a",
        "pocket card, so the citation lives here. A row at `confidence: 1` is withheld from",
        "every sheet until someone raises it -- and raising it means adding a source below,",
        "not just changing the number.",
        "",
        "| ISO | Country | Numbers | Cur | Conf | Source | URL |",
        "|---|---|---|---|---|---|---|",
    ]
    for v in sorted(verified, key=lambda z: z["code"]):
        lines.append(f"| {v['code']} | {v['name']} | `{v['numbers']}` | {v['currency']} "
                     f"| {v['confidence']} | {v['source']} | {v['url']} |")
    notes = [v for v in sorted(verified, key=lambda z: z["code"]) if v["note"]]
    if notes:
        lines += ["", "## Notes from the verifier", ""]
        for v in notes:
            lines.append(f"- **{v['code']} {v['name']}** — {v['note']}")
    NOTES_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    now_reviewed = sum(1 for r in rows.values() if int(r["confidence"] or 0) >= 2)
    print(f"{len(verified)} regions folded in, {changed} cells changed")
    print(f"{now_reviewed} of {len(rows)} regions now print their numbers")
    print(f"citations written to data/registry/regions-sources.md")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
